### ISSUE TITLE
Build status not updating for private repo.

### ISSUE THREAD

**Issue by ApsOps** [gocd-contrib/gocd-build-status-notifier#10]
The plugin just stopped working, probably because Github API library is not being updated. I have provided correct github credentials.

```java
2016-01-11 10:21:25,355 ERROR [62@MessageListener for PluginNotificationListener] BuildStatusNotifierPlugin:77 - Error occurred. Could not update build status - URL: https://github.
com/xxx/xxx.git Revision: xxx Build: xxx-pr/105/install-rebuild-test/1 Result: Failed
java.io.FileNotFoundException: {"message":"Not Found","documentation_url":"https://developer.github.com/v3"}
        at org.kohsuke.github.Requester.handleApiError(Requester.java:494)
        at org.kohsuke.github.Requester._to(Requester.java:245)
        at org.kohsuke.github.Requester.to(Requester.java:191)
        at org.kohsuke.github.GitHub.getRepository(GitHub.java:321)
        at com.tw.go.plugin.provider.github.GitHubProvider.updateCommitStatus(GitHubProvider.java:54)
        at com.tw.go.plugin.provider.github.GitHubProvider.updateStatus(GitHubProvider.java:48)
        at com.tw.go.plugin.BuildStatusNotifierPlugin.handleStageNotification(BuildStatusNotifierPlugin.java:178)
        at com.tw.go.plugin.BuildStatusNotifierPlugin.handle(BuildStatusNotifierPlugin.java:88)
        at com.thoughtworks.go.plugin.infra.DefaultPluginManager$1.execute(DefaultPluginManager.java:172)
        at com.thoughtworks.go.plugin.infra.DefaultPluginManager$1.execute(DefaultPluginManager.java:167)
        at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.executeActionOnTheService(FelixGoPluginOSGiFramework.java:315)
        at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.doOn(FelixGoPluginOSGiFramework.java:245)
        at com.thoughtworks.go.plugin.infra.DefaultPluginManager.submitTo(DefaultPluginManager.java:167)
        at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:32)
        at com.thoughtworks.go.plugin.access.notification.NotificationExtension.notify(NotificationExtension.java:74)
        at com.thoughtworks.go.server.messaging.plugin.PluginNotificationService.notifyPlugin(PluginNotificationService.java:61)
        at com.thoughtworks.go.server.messaging.plugin.PluginNotificationService.notifyPlugins(PluginNotificationService.java:53)
        at com.thoughtworks.go.server.messaging.plugin.PluginNotificationListener.onMessage(PluginNotificationListener.java:30)
        at com.thoughtworks.go.server.messaging.plugin.PluginNotificationListener.onMessage(PluginNotificationListener.java:21)
        at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.runImpl(JMSMessageListenerAdapter.java:65)
        at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.run(JMSMessageListenerAdapter.java:50)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.FileNotFoundException: https://api.github.com/repos/xxx/xxx
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1677)
        at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1675)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1673)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1246)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
        at org.kohsuke.github.Requester.parse(Requester.java:451)
        at org.kohsuke.github.Requester._to(Requester.java:224)
        ... 20 more
Caused by: java.io.FileNotFoundException: https://api.github.com/repos/xxx/xxx
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1626)
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:468)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
        at org.kohsuke.github.Requester.parse(Requester.java:447)
        ... 21 more
```

**Comment by aselus-hub** [comment]
Just tested it and getting the same thing, tested with curl and still works.

**Comment by aselus-hub** [comment]
figured out what the issue was, this has nothing to do w/ this plugin, disregard my previous statement.

**Comment by ApsOps** [comment]
@aselus-hub err.. I have no clue what your previous statement was, what's the reason for the issue or why this issue has been closed :/ @ketan

**Comment by aselus-hub** [comment]
@ApsOps after testing this, the reason for it occurring(at least in my environment) is the user (whos OAuth token is being used) that was posting the status did not have write permissions in order to write to the repo. The user must have write permissions and the OAuth token must have repo permissions in order to update statuses.
