### ISSUE TITLE
JsonParseException in org.kohsuke.github when using Github Enterprise

### ISSUE THREAD

**Issue by blind-gh0st** [gocd-contrib/gocd-build-status-notifier#128]
When trying to connect to a Github Enterprise 2.20 instance, the following error keeps appearing in the logs and there is no status indicated within Github Enterprise:

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">



  <link crossorigin="use-credentials" media="all" integrity="sha512-hddDYPWR0gBbqLRmIZP242WMEiYsVkYI2UCYCVUHB4h5DhD2cbtFJYG+HPh21dZGb+sbgDHxQBNJCBq7YbmlBQ==" rel="stylesheet" href="https://<GHE-INSTANCE>/assets/frameworks-02a3eaa24db2bd1ed9b64450595fc2cf.css" />
  <link crossorigin="use-credentials" media="all" integrity="sha512-virfO4ceMMzCPFi08e0bL1pXMXF3ykBOdO+cOkFu6hqjl/ympiylGiiYhsaumnY+oVIHNqPwmxmEeCcYGWZwlA==" re"[truncated 10882 chars]; line: 6, column: 2]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1798)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:663)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:561)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1892)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:747)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4129)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3988)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2992)
	at org.kohsuke.github.Requester.parse(Requester.java:629)
	... 23 common frames omitted
2020-09-21 20:30:19,260 ERROR [158@MessageListener for PluginNotificationMessageListener] BuildStatusNotifierPlugin:127 - Error occurred. Could not update build status - URL: https://<GHE-INSTANCE>/<ORG>/<REPO>.git Revision: 8d55ed959948ef663725fefcfefcb36b848012dc Build: <PIPELINE>/10/<STAGE>/1 Result: Passed
org.kohsuke.github.HttpException: Server returned HTTP response code: 200, message: 'OK' for URL: https://<GHE-INSTANCE>/login?return_to=https%3A%2F%2F<GHE-INSTANCE>%2Fuser
	at org.kohsuke.github.Requester.parse(Requester.java:646)
	at org.kohsuke.github.Requester.parse(Requester.java:607)
	at org.kohsuke.github.Requester._to(Requester.java:285)
	at org.kohsuke.github.Requester.to(Requester.java:247)
	at org.kohsuke.github.GitHub.getMyself(GitHub.java:384)
	at org.kohsuke.github.GitHub.<init>(GitHub.java:158)
	at org.kohsuke.github.GitHubBuilder.build(GitHubBuilder.java:207)
	at org.kohsuke.github.GitHub.connectUsingOAuth(GitHub.java:223)
	at com.tw.go.plugin.provider.GitHubProvider.createGitHubClient(GitHubProvider.java:98)
	at com.tw.go.plugin.provider.GitHubProvider.updateCommitStatus(GitHubProvider.java:82)
	at com.tw.go.plugin.provider.GitHubProvider.updateStatus(GitHubProvider.java:72)
	at com.tw.go.plugin.BuildStatusNotifierPlugin.handleStageNotification(BuildStatusNotifierPlugin.java:171)
	at com.tw.go.plugin.BuildStatusNotifierPlugin.handle(BuildStatusNotifierPlugin.java:91)
	at com.thoughtworks.go.plugin.infra.DefaultPluginManager.lambda$submitTo$0(DefaultPluginManager.java:134)
	at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.executeActionOnTheService(FelixGoPluginOSGiFramework.java:208)
	at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.doOn(FelixGoPluginOSGiFramework.java:164)
	at com.thoughtworks.go.plugin.infra.DefaultPluginManager.submitTo(DefaultPluginManager.java:131)
	at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:49)
	at com.thoughtworks.go.plugin.access.notification.NotificationExtension.notify(NotificationExtension.java:83)
	at com.thoughtworks.go.server.messaging.notifications.PluginNotificationMessageListener.onMessage(PluginNotificationMessageListener.java:44)
	at com.thoughtworks.go.server.messaging.notifications.PluginNotificationMessageListener.onMessage(PluginNotificationMessageListener.java:29)
	at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.runImpl(JMSMessageListenerAdapter.java:83)
	at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.run(JMSMessageListenerAdapter.java:63)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: (String)"
```
It seems that Jenkins has had a [very similar issue](https://issues.jenkins-ci.org/browse/JENKINS-60690). I tried using the [suggested solution](https://superuser.com/questions/1459241/jenkins-and-github-enterprise-2-17-failing-pull-request-builds-only) but it didn't help in this case. Is anyone else seeing this error? Is there a real solution that can be implemented rather than just a work-around (dependency upgrade, etc)?

**Comment by blind-gh0st** [comment]
It looks like dependabot already has a PR ready to upgrade the Github API. Can we get this tested and merged to see if it fixes the issue?

https://github.com/gocd-contrib/gocd-build-status-notifier/pull/118

**Comment by chadlwilson** [comment]
This is very old, but let us know if not working on latest.
