### ISSUE TITLE
GitHub 401 on status updates for private repo

### ISSUE THREAD

**Issue by Thalagyrt** [gocd-contrib/gocd-build-status-notifier#13]
Hiya,

This plugin is throwing 401s on every status update attempt. According to GitHub's docs, this means authentication has failed or no creds were passed at all, but the logs don't contain the json passed back by GitHub, so I can't really tell what's up. I've tried configuring the username/password using both `.github` as well as by defining GO_SERVER_SYSTEM_PROPERTIES in `/etc/default/go-server`: `export GO_SERVER_SYSTEM_PROPERTIES="-Dgo.plugin.build.status.github.username=vNucleus-GoCD -Dgo.plugin.build.status.github.password={snip}'`. Ideally I'd like to use oAuth for this, but have had no luck getting that working either. It seems as if the plugin is continually trying to authenticate as an anonymous user, ignoring all the creds I've tried throwing at it.

The `gocd-build-github-pull-requests` plugin is successfully authing and building PRs both using oAuth as well as password so I know the creds are good. It's just this status plugin that seems to be ignoring them. Any tips?

Thanks!
James

```
2016-02-06 18:03:18,401 ERROR [64@MessageListener for PluginNotificationListener] BuildStatusNotifierPlugin:77 - Error occurred. Could not update build status - URL: https://github.com/vNucleus/portal Revision: a66d5ff3cf6cf25fda393931f3a4492d7d98d697 Build: Build-PR/7/Build/1 Result: Failed
java.io.IOException: Server returned HTTP response code: 401 for URL: https://api.github.com/repos/vNucleus/portal
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1676)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1674)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1672)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1245)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at org.kohsuke.github.Requester.parse(Requester.java:451)
	at org.kohsuke.github.Requester._to(Requester.java:224)
	at org.kohsuke.github.Requester.to(Requester.java:191)
	at org.kohsuke.github.GitHub.getRepository(GitHub.java:321)
	at com.tw.go.plugin.provider.github.GitHubProvider.updateCommitStatus(GitHubProvider.java:54)
	at com.tw.go.plugin.provider.github.GitHubProvider.updateStatus(GitHubProvider.java:48)
	at com.tw.go.plugin.BuildStatusNotifierPlugin.handleStageNotification(BuildStatusNotifierPlugin.java:178)
	at com.tw.go.plugin.BuildStatusNotifierPlugin.handle(BuildStatusNotifierPlugin.java:88)
	at com.thoughtworks.go.plugin.infra.DefaultPluginManager$1.execute(DefaultPluginManager.java:172)
	at com.thoughtworks.go.plugin.infra.DefaultPluginManager$1.execute(DefaultPluginManager.java:167)
	at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.executeActionOnTheService(FelixGoPluginOSGiFramework.java:315)
	at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.doOn(FelixGoPluginOSGiFramework.java:245)
	at com.thoughtworks.go.plugin.infra.DefaultPluginManager.submitTo(DefaultPluginManager.java:167)
	at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:32)
	at com.thoughtworks.go.plugin.access.notification.NotificationExtension.notify(NotificationExtension.java:74)
	at com.thoughtworks.go.server.messaging.plugin.PluginNotificationService.notifyPlugin(PluginNotificationService.java:61)
	at com.thoughtworks.go.server.messaging.plugin.PluginNotificationService.notifyPlugins(PluginNotificationService.java:53)
	at com.thoughtworks.go.server.messaging.plugin.PluginNotificationListener.onMessage(PluginNotificationListener.java:30)
	at com.thoughtworks.go.server.messaging.plugin.PluginNotificationListener.onMessage(PluginNotificationListener.java:21)
	at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.runImpl(JMSMessageListenerAdapter.java:65)
	at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.run(JMSMessageListenerAdapter.java:50)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Server returned HTTP response code: 401 for URL: https://api.github.com/repos/vNucleus/portal
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1627)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:468)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
	at org.kohsuke.github.Requester.parse(Requester.java:447)
	... 21 more
```

**Comment by Thalagyrt** [comment]
Ahhh, figured it out. The docs weren't clear on username/password in the configuration for the plugin in the UI. Since it was asking for the GoCD base url, I thought these creds were for GoCD. Working perfectly now!
