### ISSUE TITLE
Could not update build status - Error occurred. Status Code: 404

### ISSUE THREAD

**Issue by dokaspar** [gocd-contrib/gocd-build-status-notifier#29]
Hi,

I've installed the stash-pr-status-1.3.jar on our GoCD 17.8.0 server and configured it with Server URL and End Point both set to http://localhost:8153. A user/password is also configured with access to our BitBucket server.

The "Stash Pull Requests Builder" (ashwanthkumar/gocd-build-github-pull-requests) plugin properly triggers a new build when a pull request is created. And also the status notifier plugin triggers, but keeps logging the error below. I'm out of ideas about what's wrong:
- the git URL is definitely correct (no idea why there's a 404...)
- the configured user has admin permissions

Any pointers would be highly appreciated

Regards,
Dominik

`2017-09-15 16:05:08,091 ERROR [73@MessageListener for PluginNotificationListener] BuildStatusNotifierPlugin:77 - Error occurred. Could not update build status - URL: ssh://git@git.example.com:7999/~dokaspar/tools.git Revision: 400d88363337d6b12b6a1fc14d0ad13662783218 Build: dokaspar-test-pr/14/defaultStage/1 Result: Passed
java.lang.RuntimeException: Error occurred. Status Code: 404
	at com.tw.go.plugin.util.HTTPClient.postRequest(HTTPClient.java:73)
	at com.tw.go.plugin.provider.stash.StashProvider.updateStatus(StashProvider.java:73)
	at com.tw.go.plugin.BuildStatusNotifierPlugin.handleStageNotification(BuildStatusNotifierPlugin.java:160)
	at com.tw.go.plugin.BuildStatusNotifierPlugin.handle(BuildStatusNotifierPlugin.java:84)
	at com.thoughtworks.go.plugin.infra.DefaultPluginManager$2.execute(DefaultPluginManager.java:166)
	at com.thoughtworks.go.plugin.infra.DefaultPluginManager$2.execute(DefaultPluginManager.java:161)
	at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.executeActionOnTheService(FelixGoPluginOSGiFramework.java:315)
	at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.doOn(FelixGoPluginOSGiFramework.java:245)
	at com.thoughtworks.go.plugin.infra.DefaultPluginManager.submitTo(DefaultPluginManager.java:161)
	at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:32)
	at com.thoughtworks.go.plugin.access.notification.NotificationExtension.notify(NotificationExtension.java:72)
	at com.thoughtworks.go.server.messaging.plugin.PluginNotificationService.notifyPlugin(PluginNotificationService.java:61)
	at com.thoughtworks.go.server.messaging.plugin.PluginNotificationService.notifyPlugins(PluginNotificationService.java:53)
	at com.thoughtworks.go.server.messaging.plugin.PluginNotificationListener.onMessage(PluginNotificationListener.java:30)
	at com.thoughtworks.go.server.messaging.plugin.PluginNotificationListener.onMessage(PluginNotificationListener.java:21)
	at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.runImpl(JMSMessageListenerAdapter.java:73)
	at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.run(JMSMessageListenerAdapter.java:53)
	at java.lang.Thread.run(Thread.java:745)`

**Comment by dokaspar** [comment]
In case of Bitbucket, the "End Point" must point to the Bitbucket base URL, for example:
`https://example.xom:8444/bitbucket`
