### ISSUE TITLE
No longer works

### ISSUE THREAD

**Issue by ketan** [gocd-contrib/gocd-build-status-notifier#35]
I see the following in the logs. Here's a [fix](https://github.com/kohsuke/github-api/commit/7735edeae87652c1fa8196e7956851a39f5a84d4) in the upstream library that should resolve the issue.

```
2017-11-14 21:23:53,522 ERROR [76@MessageListener for PluginNotificationListener] BuildStatusNotifierPlugin:82 - Error occurred. Could not update build status - URL: https://mirrors.gocd.org/git/gocd/gocd Revision: 3eafdcc875eea114601ce7b9e65f52b26a7d52cf Build: build-windows-PR/1993/build-non-server/5 Result: Failed
java.io.IOException: Failed to deserialize {"url":"https://api.github.com/repos/gocd/gocd/statuses/3eafdcc875eea114601ce7b9e65f52b26a7d52cf","id":4316650825,"state":"failure","description":"","target_url":"https://build.gocd.org/go/pipelines/build-windows-PR/1993/build-non-server/5","context":"build-windows-PR/build-non-server","created_at":"2017-11-15T02:23:53Z","updated_at":"2017-11-15T02:23:53Z","creator":{"login":"gocd-ci-user","id":12554687,"avatar_url":"https://avatars0.githubusercontent.com/u/12554687?v=4","gravatar_id":"","url":"https://api.github.com/users/gocd-ci-user","html_url":"https://github.com/gocd-ci-user","followers_url":"https://api.github.com/users/gocd-ci-user/followers","following_url":"https://api.github.com/users/gocd-ci-user/following{/other_user}","gists_url":"https://api.github.com/users/gocd-ci-user/gists{/gist_id}","starred_url":"https://api.github.com/users/gocd-ci-user/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/gocd-ci-user/subscriptions","organizations_url":"https://api.github.com/users/gocd-ci-user/orgs","repos_url":"https://api.github.com/users/gocd-ci-user/repos","events_url":"https://api.github.com/users/gocd-ci-user/events{/privacy}","received_events_url":"https://api.github.com/users/gocd-ci-user/received_events","type":"User","site_admin":false}}
	at org.kohsuke.github.Requester.parse(Requester.java:457)
	at org.kohsuke.github.Requester._to(Requester.java:224)
	at org.kohsuke.github.Requester.to(Requester.java:191)
	at org.kohsuke.github.GHRepository.createCommitStatus(GHRepository.java:780)
	at com.tw.go.plugin.provider.github.GitHubProvider.updateCommitStatus(GitHubProvider.java:69)
	at com.tw.go.plugin.provider.github.GitHubProvider.updateStatus(GitHubProvider.java:57)
	at com.tw.go.plugin.BuildStatusNotifierPlugin.handleStageNotification(BuildStatusNotifierPlugin.java:160)
	at com.tw.go.plugin.BuildStatusNotifierPlugin.handle(BuildStatusNotifierPlugin.java:84)
	at com.thoughtworks.go.plugin.infra.DefaultPluginManager$2.execute(DefaultPluginManager.java:167)
	at com.thoughtworks.go.plugin.infra.DefaultPluginManager$2.execute(DefaultPluginManager.java:162)
	at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.executeActionOnTheService(FelixGoPluginOSGiFramework.java:316)
	at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.doOn(FelixGoPluginOSGiFramework.java:246)
	at com.thoughtworks.go.plugin.infra.DefaultPluginManager.submitTo(DefaultPluginManager.java:162)
	at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:48)
	at com.thoughtworks.go.plugin.access.notification.NotificationExtension.notify(NotificationExtension.java:72)
	at com.thoughtworks.go.server.messaging.plugin.PluginNotificationService.notifyPlugin(PluginNotificationService.java:62)
	at com.thoughtworks.go.server.messaging.plugin.PluginNotificationService.notifyPlugins(PluginNotificationService.java:54)
	at com.thoughtworks.go.server.messaging.plugin.PluginNotificationListener.onMessage(PluginNotificationListener.java:30)
	at com.thoughtworks.go.server.messaging.plugin.PluginNotificationListener.onMessage(PluginNotificationListener.java:21)
	at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.runImpl(JMSMessageListenerAdapter.java:73)
	at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.run(JMSMessageListenerAdapter.java:53)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Numeric value (4316650825) out of range of int
 at [Source: java.io.StringReader@438f00f6; line: 1, column: 114] (through reference chain: org.kohsuke.github.GHCommitStatus["id"])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:232)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:197)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1311)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:297)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:121)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:2888)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2034)
	at org.kohsuke.github.Requester.parse(Requester.java:455)
	... 21 common frames omitted
Caused by: com.fasterxml.jackson.core.JsonParseException: Numeric value (4316650825) out of range of int
 at [Source: java.io.StringReader@438f00f6; line: 1, column: 114]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1369)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:532)
	at com.fasterxml.jackson.core.base.ParserBase.convertNumberToInt(ParserBase.java:847)
	at com.fasterxml.jackson.core.base.ParserBase.getIntValue(ParserBase.java:643)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer._parseInteger(StdDeserializer.java:306)
	at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$IntegerDeserializer.deserialize(NumberDeserializers.java:319)
	at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$IntegerDeserializer.deserialize(NumberDeserializers.java:301)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:464)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:107)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:295)
	... 25 common frames omitted
```

**Comment by ketan** [comment]
Closing via #36
