### ISSUE TITLE
Github Enterprise not receiving status report from plugin using ~/.github

### ISSUE THREAD

**Issue by maufonfa** [gocd-contrib/gocd-build-status-notifier#68]
Github enterprise triggers the pipeline in GoCD. After the pipeline finishes no report is received back in Github.
I'm using ~/.github file and the content of this file is:
endpoint=http://githuben.mycompany.com/api/v3
login=Name_LastName
oauth=xxxxxxxxxxxxxxxx

GoCD Version 19.4.0 in both server and agents. Plugin version is 1.6-73

**Comment by maufonfa** [comment]
GoCD Version 19.4.0 in both server and agents. Plugin version is 1.6-73

**Comment by vrushaliwaykole** [comment]
> Github enterprise triggers the pipeline in GoCD. After the pipeline finishes no report is received back in Github.
> I'm using ~/.github file and the content of this file is:
> endpoint=http://githuben.mycompany.com/api/v3
> login=Name_LastName
> oauth=xxxxxxxxxxxxxxxx
> 
> GoCD Version 19.4.0 in both server and agents. Plugin version is 1.6-73

@maufonfa 
Can you check if there are any errors in logs of `github.pr.status` plugin? and if there are any, can you please provide the logs?

**Comment by maufonfa** [comment]
@vrushaliwaykole where can I find these logs if you don't mind me asking?

**Comment by maufonfa** [comment]
@vrushaliwaykole here:

2019-06-05 11:04:02,325 ERROR [153@MessageListener for PluginNotificationMessageListener] BuildStatusNotifierPlugin:128 - Error occurred. Could not update build status - URL: http://XXX/ Revision: 74d98ea88224399daaf2c42b969dfd95f52fe3bc Build: iam_ut_dev/81/unit_testing/1 Result: Unknown
org.kohsuke.github.HttpException: Server returned HTTP response code: 301, message: 'Moved Permanently' for URL: http://XXX/api/v3/repos/
at org.kohsuke.github.Requester.parse(Requester.java:646)
at org.kohsuke.github.Requester.parse(Requester.java:607)
at org.kohsuke.github.Requester._to(Requester.java:285)
at org.kohsuke.github.Requester.to(Requester.java:247)
at org.kohsuke.github.GitHub.getRepository(GitHub.java:475)
at com.tw.go.plugin.provider.GitHubProvider.updateCommitStatus(GitHubProvider.java:83)
at com.tw.go.plugin.provider.GitHubProvider.updateStatus(GitHubProvider.java:72)
at com.tw.go.plugin.BuildStatusNotifierPlugin.handleStageNotification(BuildStatusNotifierPlugin.java:171)
at com.tw.go.plugin.BuildStatusNotifierPlugin.handle(BuildStatusNotifierPlugin.java:91)
at com.thoughtworks.go.plugin.infra.DefaultPluginManager.lambda$submitTo$0(DefaultPluginManager.java:153)
at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.executeActionOnTheService(FelixGoPluginOSGiFramework.java:304)
at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.doOn(FelixGoPluginOSGiFramework.java:246)
at com.thoughtworks.go.plugin.infra.DefaultPluginManager.submitTo(DefaultPluginManager.java:150)
at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:49)
at com.thoughtworks.go.plugin.access.notification.NotificationExtension.notify(NotificationExtension.java:84)
at com.thoughtworks.go.server.messaging.notifications.PluginNotificationMessageListener.onMessage(PluginNotificationMessageListener.java:45)
at com.thoughtworks.go.server.messaging.notifications.PluginNotificationMessageListener.onMessage(PluginNotificationMessageListener.java:30)
at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.runImpl(JMSMessageListenerAdapter.java:86)
at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.run(JMSMessageListenerAdapter.java:66)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Failed to deserialize
at org.kohsuke.github.Requester.parse(Requester.java:631)
... 19 common frames omitted
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
at [Source: (String)""; line: 1, column: 0]
at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4133)
at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3988)
at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2992)
at org.kohsuke.github.Requester.parse(Requester.java:629)
... 19 common frames omitted
2019-06-05 11:04:59,224 ERROR [153@MessageListener for PluginNotificationMessageListener] BuildStatusNotifierPlugin:128 - Error occurred. Could not update build status - URL: http://XXX/ Revision: 74d98ea88224399daaf2c42b969dfd95f52fe3bc Build: iam_ut_dev/81/unit_testing/1 Result: Passed
org.kohsuke.github.HttpException: Server returned HTTP response code: 301, message: 'Moved Permanently' for URL: http://XXX/api/v3/repos/
at org.kohsuke.github.Requester.parse(Requester.java:646)
at org.kohsuke.github.Requester.parse(Requester.java:607)
at org.kohsuke.github.Requester._to(Requester.java:285)
at org.kohsuke.github.Requester.to(Requester.java:247)
at org.kohsuke.github.GitHub.getRepository(GitHub.java:475)
at com.tw.go.plugin.provider.GitHubProvider.updateCommitStatus(GitHubProvider.java:83)
at com.tw.go.plugin.provider.GitHubProvider.updateStatus(GitHubProvider.java:72)
at com.tw.go.plugin.BuildStatusNotifierPlugin.handleStageNotification(BuildStatusNotifierPlugin.java:171)
at com.tw.go.plugin.BuildStatusNotifierPlugin.handle(BuildStatusNotifierPlugin.java:91)
at com.thoughtworks.go.plugin.infra.DefaultPluginManager.lambda$submitTo$0(DefaultPluginManager.java:153)
at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.executeActionOnTheService(FelixGoPluginOSGiFramework.java:304)
at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.doOn(FelixGoPluginOSGiFramework.java:246)
at com.thoughtworks.go.plugin.infra.DefaultPluginManager.submitTo(DefaultPluginManager.java:150)
at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:49)
at com.thoughtworks.go.plugin.access.notification.NotificationExtension.notify(NotificationExtension.java:84)
at com.thoughtworks.go.server.messaging.notifications.PluginNotificationMessageListener.onMessage(PluginNotificationMessageListener.java:45)
at com.thoughtworks.go.server.messaging.notifications.PluginNotificationMessageListener.onMessage(PluginNotificationMessageListener.java:30)
at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.runImpl(JMSMessageListenerAdapter.java:86)
at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.run(JMSMessageListenerAdapter.java:66)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Failed to deserialize
at org.kohsuke.github.Requester.parse(Requester.java:631)
... 19 common frames omitted
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
at [Source: (String)""; line: 1, column: 0]
at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4133)
at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3988)
at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2992)
at org.kohsuke.github.Requester.parse(Requester.java:629)
... 19 common frames omitted

**Comment by arvindsv** [comment]
I think it's redirecting to https and your configuration has http. Maybe.

You could try: `curl -v http://githuben.mycompany.com/api/v3` and see what it shows.

**Comment by maufonfa** [comment]
@arvindsv in the github file I'm pointin to https and not http, but it still does the connection to http. So the .github file is been ignored by the plugin

**Comment by arvindsv** [comment]
@maufonfa Is `~/.github` in the right home directory? Meaning the home directory of the GoCD server user. Usually, that is `/home/go` I think. I'd suggest providing a completely wrong URL such as: `https://abcd.example.com` or something, and trying to place the `.github` file in the right location, to make sure the plugin is reading from it.

**Comment by maufonfa** [comment]
@arvindsv I found that there's a special configuration in my case and the file that's reading is in /var/go and not /home/go. Thanks for the help.

I'm closing this.
